name: Update Profile Views
on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes (GitHub's minimum)
  workflow_dispatch:
jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches entire commit history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update view count
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          pip install pymongo
          python update_views.py
          
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase  # Sync with remote first
          git add views.txt
          git commit -m "Update view count [skip ci]"
          git push
