name: Update Profile Views
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Gets complete history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Update view count
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          pip install pymongo
          python update_views.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Configure git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Reset and sync with remote
          git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git"
          git fetch origin
          git reset --hard origin/main
          
          # Add and commit changes
          git add views.txt
          git commit -m "Update view count [skip ci]"
          
          # Force push (since we've properly reset)
          git push origin main
