name: Update Profile Views
on:
  schedule:
    - cron: '*/5 * * * *'  
  repository_dispatch: 
jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Update view count
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          pip install pymongo
          python update_views.py
          
      - name: Generate views.json
        run: |
          echo '{"views": $(cat views.txt)}' > views.json
          
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin "https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git"
          git add views.txt views.json
          git commit -m "Update view count [skip ci]"
          git push
